### ISSUE TITLE
Execution of trajectories

### ISSUE THREAD

**Issue by Makekihe** [mSimon12/multiple_quadrotors#1]
Hello mSimon, 

We've talked previously on wilselby's GitHub [(#46)](https://github.com/wilselby/ROS_quadrotor_simulator/issues/46) with regards to performing 3D navigation of the Hector quadrotor in Moveit. I found it more suiting to continue the conversation here. I'm hoping that you can help me out if you have the time. 

I've managed to compile both your and Tahsinkose's package on Kinetic (for whatever reason, this worked better than Melodic), and I've tried to understand the packages which you've used and developed. 
1. It seems like you both have created an action server (trajectory_action_pkg or hector_moveit_actions) and a secondary package for executing the trajectories which are developed in Moveit (quadrotor_control_system or hector_moveit_exploration). I'm interested in the go-to-goal/follow trajectory (with obstacle avoidance) functionality which it seems like you've developed inside your move_drone.py, yet I have no idea how to create this functionality myself. Are there any guides I can use to create similar packages?

2. If I'm allowed to use your package (with your permission of cause), how can I incorporate it into my own workspace?

3. I've tried to launch your package the way you've described here on your Github, however, RViz cannot open when using the `roslaunch full_system_launcher system.launch` command. It just remains at the loading window, as seen on the picture below. Note that Gazebo loads without problems. Furthermore, when using the `rosrun quadrotor_control_system move_drone.py drone_name X Y Z THETA` command, nothing happens (I assume this is because RViz refuses to load, but it could be something else). Do you know how to fix this?
![127089655_2492385384395267_8379033823060756314_n](https://user-images.githubusercontent.com/34446346/100099287-8569b400-2e5f-11eb-94d3-976ece5e3bd1.png)
![127242227_3755740141137783_5112371183088084441_n](https://user-images.githubusercontent.com/34446346/100099992-70d9eb80-2e60-11eb-9bd5-60879eda43d5.png)

**Comment by mSimon12** [comment]
Hi @Makekihe ,

Sorry for the delay.

> 1. It seems like you both have created an action server (trajectory_action_pkg or hector_moveit_actions) and a secondary package for executing the trajectories which are developed in Moveit (quadrotor_control_system or hector_moveit_exploration). I'm interested in the go-to-goal/follow trajectory (with obstacle avoidance) functionality which it seems like you've developed inside your move_drone.py, yet I have no idea how to create this functionality myself. Are there any guides I can use to create similar packages?

The **trajectory_action_pkg** is the package where I have implemented the action responsible for calling moveit planning, to avoid collisions, and translate it into the motion execution.

> 2. If I'm allowed to use your package (with your permission of cause), how can I incorporate it into my own workspace?

If you desire to apply the motion directly into a code implemented by you, the best option is to copy the code into the **move_drone.py**. It basicaly creates a client of the action that I have created and send the desired position.

> 3. I've tried to launch your package the way you've described here on your Github, however, RViz cannot open when using the roslaunch full_system_launcher system.launch command. It just remains at the loading window, as seen on the picture below. Note that Gazebo loads without problems. Furthermore, when using the rosrun quadrotor_control_system move_drone.py drone_name X Y Z THETA command, nothing happens (I assume this is because RViz refuses to load, but it could be something else). Do you know how to fix this?

By  default, my launch starts with the Gazebo paused. Have you started it? 

*Rviz opens only after you start the Gazebo.
